# fly.toml app configuration file generated for teeatr on 2026-06-13T09:54:54Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
# ADR: ADR-0027

app = 'teeatr'
primary_region = 'iad'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    method = 'get'
    path = '/'
    interval = '15s'
    timeout = '5s'
    grace_period = '10s'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
